nelmio_api_doc:
  areas:
    path_patterns: # an array of regexps
      - ^/api/
    host_patterns:
      - ^api\.
  documentation:
    schemes: [http, https]
    info:
      title: Dicehoarders API
      description: This is the dicehoarders api spec and I suck at naming things!
      version: 1.0.0
