CREATE TABLE ammunition (
    id INT NOT NULL PRIMARY KEY,
    base_ammunition_id INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);