CREATE TABLE sf_user (
    id INT NOT NULL AUTO_INCREMENT,
    email VARCHAR(180) NOT NULL UNIQUE,
    username VARCHAR(180) NOT NULL UNIQUE,
    validated DATETIME,
    roles JSON NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
