CREATE TABLE campaign (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    join_code VARCHAR(12) UNIQUE NOT NULL,
    join_unlocked BOOL NOT NULL DEFAULT TRUE,
    creator INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
